### ISSUE TITLE
smartctl fails to access drive

### ISSUE THREAD

**Issue by TeamLinux01** [linuxserver/docker-scrutiny#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Passing the device from the host via "volumes" does not allow smartctl to perform operations using the example docker-compose. Changing the compose file to use "devices" section will allow smartctl to work correctly.

------------------------------

## Expected Behavior
smartctl should read attribute data from the storage drive that is passed to the container.

## Current Behavior
Smartctl open device: /dev/sda failed: Operation not permitted

## Steps to Reproduce
docker-compose up -d
docker exec scrutiny smartctl -a /dev/sda

## Environment
**OS: Ubuntu server 20.04
**CPU architecture: x86_64      
**How docker service was installed: apt install docker.io      

## Command used to create docker container (run/create/compose/screenshot)
docker-compose.yml
```yaml
---
version: "2.1"
services:
  scrutiny:
    ...
    volumes:
      - /dev/sda:/dev/sda:ro
    ...
```
## Workable fix
Remove the sd* device/s from volumes and create entries under devices.

docker-compose.yml
```yaml
---
version: "2.1"
services:
  scrutiny:
    ...
    devices:
      - /dev/sda
    ...
```
