### ISSUE TITLE
Updated Scrutiny image does not start - "panic: a username and password is required for a setup"

### ISSUE THREAD

**Issue by teejo75** [linuxserver/docker-scrutiny#22]
## Expected Behavior
Container should start and provide access

## Current Behavior
Container is looping with an error

## Steps to Reproduce

1. docker-compose up -d
2. docker-compose logs
3.
4.

## Environment
**OS:** Debian Bullseye
**CPU architecture:** x86_64
**How docker service was installed:**  Official docker-ce

## Command used to create docker container (run/create/compose/screenshot)
Compose is the same as the example, except for own devices added.

## Docker logs
scrutiny_1  |  ___   ___  ____  __  __  ____  ____  _  _  _  _                                                                                                                   
scrutiny_1  | / __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )                                                                                                                  
scrutiny_1  | \__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /                                                                                                                   
scrutiny_1  | (___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)                                                                                                                   
scrutiny_1  | github.com/AnalogJ/scrutiny                             dev-0.4.3                                                                                                  
scrutiny_1  |                                                                                                                                                                    
scrutiny_1  | Start the scrutiny server                                                                                                                                          
scrutiny_1  | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
scrutiny_1  |  - using env:     export GIN_MODE=release
scrutiny_1  |  - using code:    gin.SetMode(gin.ReleaseMode)
scrutiny_1  |                                                                                                                                                                    
scrutiny_1  | time="2022-05-12T10:15:15+10:00" level=info msg="Trying to connect to scrutiny sqlite db: \n"
scrutiny_1  | time="2022-05-12T10:15:15+10:00" level=info msg="Successfully connected to scrutiny sqlite db: \n"           
scrutiny_1  | panic: a username and password is required for a setup   
scrutiny_1  |                                                                                                                                                                    
scrutiny_1  | goroutine 1 [running]:                                                    
scrutiny_1  | github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware({0xfeaac0, 0xc000010ce8}, {0xff3d50, 0xc0004a6070})
scrutiny_1  |   /app/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xa5
scrutiny_1  | github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc0004a0650, {0xff3d50, 0xc0004a6070})
scrutiny_1  |   /app/scrutiny/webapp/backend/pkg/web/server.go:26 +0xb4               
scrutiny_1  | github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc0004a0650)                         
scrutiny_1  |   /app/scrutiny/webapp/backend/pkg/web/server.go:97 +0x3ab          
scrutiny_1  | main.main.func2(0xc000329c00)                                             
scrutiny_1  |   /app/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x1f7
scrutiny_1  | github.com/urfave/cli/v2.(*Command).Run(0xc0004a8000, 0xc000329a80)
scrutiny_1  |   /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x64a
scrutiny_1  | github.com/urfave/cli/v2.(*App).RunContext(0xc000290480, {0xfd4dd0, 0xc000036058}, {0xc000032040, 0x2, 0x2})
scrutiny_1  |   /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x926
scrutiny_1  | github.com/urfave/cli/v2.(*App).Run(...)
scrutiny_1  |   /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
scrutiny_1  | main.main()
scrutiny_1  |   /app/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x679
scrutiny_1  | 2022/05/12 10:15:16 No configuration file found at /opt/scrutiny/config/scrutiny.yaml. Using Defaults.

**Comment by Dubbeldrank** [comment]
Same problem here.

**Comment by Forceflow** [comment]
I'm also seeing this behaviour on Ubuntu 22.04, 64-bit.

Using the default config. Even with no disks attached to the container, the image just seems to be panicking and restarting.

**Comment by rhavinx** [comment]
I have the same issue.

**Comment by alexbelgium** [comment]
Same, had to go back to *-ls34 to avoid this issue

**Comment by papukj** [comment]
It appears that this issue is caused by a missing influx database. 
https://github.com/AnalogJ/scrutiny/issues/234

**Comment by ragebflame** [comment]
> Same, had to go back to *-ls34 to avoid this issue

Thanks, this get this back up and running for now.

**Comment by derekcentrico** [comment]
Yes, I ended up going to analogj's build using this docker-compose structure while waiting for Linuxserver to either 1) fix this or 2) delete support for scrutiny.  The docker chat seemed to indicate a negative stance because it breaks their principles to include influxdb into the Linuxserver docker container.

```
  scrutinyanalogj:
    ports:
      - '86:80'
      - '8886:8080'
    volumes:
      - '/path/to/docker/scrutinyanalogj:/opt/scrutiny/config'
      - '/path/to/docker/influxdb2:/opt/scrutiny/influxdb'
      - '/run/udev:/run/udev:ro'
    restart: always
    logging:
      options:
        max-size: 1g
    container_name: scrutinyanalogj
    environment:
      - PUID=1000
      - PGID=996
      - TZ=America/New_York
    devices:
      - '/dev/nvme0n1p1:/dev/nvme0n1p1'
      - '/dev/nvme1n1p1:/dev/nvme1n1p1'
      - '/dev/sdc:/dev/sdc'
      - '/dev/sdb:/dev/sdb'
      - '/dev/sda:/dev/sda'
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    image: ghcr.io/analogj/scrutiny:master-omnibus
```

Of note, I use these odd ports (one up from the normal container) because I have Linuxserver's container still setup.  Hoping one day against all odds it'll fix and I can keep with it.
